services:
  debt-display:
    build:
      context: .
      network: host
    container_name: debt-display
    restart: unless-stopped
    ports:
      - "3300:3300"
    volumes:
      - type: bind
        source: ${DEBT_DISPLAY_DATA_DIR:-./data}
        target: /data
